# Generated by Django 4.1.6 on 2023-05-10 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("device_os", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "device_os_version",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "device_browser",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "device_browser_version",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "device_token",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("profile", "device_id")},
            },
        ),
    ]
