# Generated by Django 4.1.6 on 2023-05-23 10:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_result_options_alter_result_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="at_work_from",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="at_work_to",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="work",
            field=models.CharField(
                blank=True, choices=[("1", "Yes"), ("0", "No")], max_length=1, null=True
            ),
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("see_at_work", models.BooleanField(default=False)),
                ("see_at_weekend", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.category"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
    ]
