# Generated by Django 4.1.6 on 2023-05-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_at_work_from_profile_at_work_to_profile_work_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="preference",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="preference",
            unique_together={("profile", "category")},
        ),
    ]
