# Generated by Django 4.2.1 on 2023-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_preference_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preference_facts',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
