# Generated by Django 4.2.1 on 2023-05-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_preference_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gorcias',
            field=models.BooleanField(default=False),
        ),
    ]
